2011-12-17T18:03:00.000Z	bullgard6		'~$ computer-janitor-gtk; ERROR:dbus.proxies:Introspect error on :1.57:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 1 matched rules; type="method_call", sender=":1.106" (uid=1000 pid=5868 comm="/usr/bin/python /usr/sbin/computer-janitor-gtk ") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)"...
2011-12-17T18:03:00.000Z	bullgard6		...requested_reply="0" destination=":1.57" (uid=0 pid=3190 comm="/usr/bin/python /usr/share/computerjanitor/janitor"); ERROR:computerjanitor:org.freedesktop.DBus.Python.OSError: Traceback (most recent call last):   File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 702, in _message_cb     retval = candidate_method(self, *args, **keywords)..." How can I terminate this traceback...
2011-12-17T18:03:00.000Z	bullgard6		...program so thatI can use  this terminal window normally?
2011-12-17T18:03:00.000Z	FloodBot1	bullgard6	Please don't flood; use http://paste.ubuntu.com to paste; don't use Enter as punctuation.
