2012-02-15T00:31:00.000Z	cloudgeek		i tried to access my python app
2012-02-15T00:31:00.000Z	cloudgeek		python manage.py runserver 192.168.1.2:80
2012-02-15T00:31:00.000Z	cloudgeek		is saying that you don't have permission use that port with root too
2012-02-15T00:33:00.000Z	blitz	cloudgeek	try ps -ef | grep python
